# Setup
title:               Raquib Khan Lavani
tagline:             'Software @UAlberta'
description:         'Check out my <a href="https://www.linkedin.com/in/lavani/" target="_blank">Linkedin</a>.'
url:                 https://www.linkedin.com/in/lavani/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Raquib Khan Lavani
  url:               https://www.linkedin.com/in/lavani/
  email:             lavani@ualberta.ca

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
